// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import CopysymbolController from "./copysymbol_controller"
application.register("copysymbol", CopysymbolController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import LoginController from "./login_controller"
application.register("login", LoginController)

import PreviewController from "./preview_controller"
application.register("preview", PreviewController)
